/**
 * Builds one 128x128 tile texture per terrain type out of game-icons.net glyphs.
 *
 * The glyphs are monochrome vectors, so the output is a white motif on transparency:
 * it sits over TerrainDefinition.baseColor and inherits the palette instead of fighting
 * it. That is what keeps these from clashing with the hand-made unit art — a pixel-art
 * tileset would.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';

// The icon library, as vendored in this repo. It used to point at a scratchpad directory from
// the session that first ran this, which survived by luck — a regenerate script whose source
// lives outside the repo is a script that stops working the day nobody notices.
const SRC = process.env.ICONS_SRC || join(import.meta.dirname, 'game-icons');
const OUT = 'D:/Users/tuanla2/game/plants-into-the-breach/public/img/terrain';

// terrain -> [artist/file, opacity, motif count]. Opacity is tuned per terrain: ground the
// player walks on stays quiet, hazards and walls read loud enough to be seen at a glance.
const MAP = {
    GRASS:      ['delapouite/high-grass',    0.13, 'scatter'],
    WATER:      ['lorc/waves',               0.16, 'rows'],
    CONCRETE:   ['delapouite/stone-path',    0.14, 'single'],
    LAVA:       ['sbed/lava',                0.20, 'scatter'],
    ICE:        ['lorc/snowflake-2',         0.16, 'scatter'],
    SAND:       ['delapouite/desert',        0.13, 'single'],
    MOUNTAIN:   ['lorc/mountains',           0.26, 'single'],
    POWER_TILE: ['lorc/energise',            0.22, 'single'],
    SMOKE:      ['lorc/dust-cloud',          0.18, 'scatter'],
    FIRE:       ['carl-olsen/flame',         0.22, 'scatter'],
    WALL:       ['delapouite/brick-wall',    0.24, 'single'],
    BRIDGE:     ['delapouite/packed-planks', 0.20, 'single'],
    RAIL:       ['delapouite/rail-road',     0.20, 'single'],
    // Thornquill's spine field. NOT a terrain type — it is an overlay on whatever ground is
    // already there (TileData.spikes), so it is drawn on top rather than instead. Loud, at the
    // hazard end of the opacity range: it damages everything that walks in, it expires on a
    // clock, and a hazard the player cannot see is a promise of perfect information broken.
    SPIKES:     ['delapouite/caltrops',      0.34, 'scatter'],
};

/**
 * The house row is not terrain — it is the win condition, and Tile.tsx paints it itself. It
 * gets its own pair of images because the two states have to be readable apart at a glance
 * across the board: a district that still has a brain, and one that has gone dark.
 *
 * Each entry is [artist/file, opacity, x, y, scale] in 128-space. Louder than the terrain
 * motifs on purpose — these tiles are what the whole match is about.
 */
const HOUSES = {
    'house-brain': [
        ['delapouite/modern-city', 0.30, 64, 84, 0.86],
        ['lorc/brain',       0.50, 64, 34, 0.34],
    ],
    // Same skyline, no brain, and dimmed: the lights went out here.
    'house-empty': [
        ['delapouite/modern-city', 0.15, 64, 84, 0.86],
    ],
};

/**
 * Board markers that are not terrain either. Same [file, opacity, x, y, scale] shape as
 * HOUSES, and generated by the same loop.
 */
const MARKERS = {
    // Where zombies climb out next turn. Was a Lucide hand icon floating over a brown
    // ellipse, which read as a glove rather than a grave.
    'spawn-hole': [['skoll/raise-zombie', 0.55, 64, 66, 0.92]],
};

// Layouts in 128-space: [x, y, scale, rotation].
const LAYOUTS = {
    single:  [[64, 64, 0.78, 0]],
    scatter: [[34, 32, 0.34, -12], [96, 40, 0.30, 14], [26, 92, 0.30, 8], [92, 100, 0.36, -6], [64, 64, 0.26, 20]],
    rows:    [[32, 40, 0.42, 0], [96, 40, 0.42, 0], [32, 92, 0.42, 0], [96, 92, 0.42, 0]],
};

/** game-icons files open with a full-bleed black background path; everything after it is the glyph. */
const extractGlyph = (svg) => {
    const paths = [...svg.matchAll(/<path\b[^>]*\/>/g)].map(m => m[0]);
    const glyph = paths.filter(p => !/d="M0 0h512v512H0z"/.test(p));
    if (glyph.length === 0) throw new Error('no glyph paths found');
    // Force white so the motif is recolourable by opacity alone.
    return glyph.map(p => p.replace(/fill="[^"]*"/, 'fill="#ffffff"'))
                .map(p => /fill=/.test(p) ? p : p.replace('<path', '<path fill="#ffffff"'))
                .join('');
};

mkdirSync(OUT, { recursive: true });

for (const [terrain, [file, opacity, layoutName]] of Object.entries(MAP)) {
    const glyph = extractGlyph(readFileSync(join(SRC, `${file}.svg`), 'utf8'));
    const layout = LAYOUTS[layoutName];

    const uses = layout.map(([x, y, scale, rot]) => {
        // Icons are authored in a 512 box; centre it on (x,y) then scale/rotate about that point.
        const s = (128 / 512) * scale;
        return `<g transform="translate(${x} ${y}) rotate(${rot}) scale(${s}) translate(-256 -256)">${glyph}</g>`;
    }).join('');

    const out = `<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 128 128">`
        + `<g opacity="${opacity}">${uses}</g></svg>`;

    const name = terrain.toLowerCase().replace(/_/g, '-');
    writeFileSync(join(OUT, `${name}.svg`), out);
    console.log(`${name}.svg  <- ${file}  op=${opacity} ${layoutName}`);
}

for (const [name, layers] of Object.entries({ ...HOUSES, ...MARKERS })) {
    // One <g> per layer, because each carries its own opacity — unlike the terrain tiles,
    // where a single motif is repeated at one strength.
    const body = layers.map(([file, opacity, x, y, scale]) => {
        const glyph = extractGlyph(readFileSync(join(SRC, `${file}.svg`), 'utf8'));
        const s = (128 / 512) * scale;
        return `<g opacity="${opacity}" transform="translate(${x} ${y}) scale(${s}) translate(-256 -256)">${glyph}</g>`;
    }).join('');

    writeFileSync(join(OUT, `${name}.svg`),
        `<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 128 128">${body}</svg>`);
    console.log(`${name}.svg  <- ${layers.map(l => l[0]).join(' + ')}`);
}
